#This is a program that produces the times tables for a number entered by the user.
print("Enter the number that you would like the times tables of: ")
number = int(input())
print(f"1 x {number} = {1 * number}")
print(f"2 x {number} = {2 * number}")
print(f"3 x {number} = {3 * number}")
print(f"4 x {number} = {4 * number}")
print(f"5 x {number} = {5 * number}")
print(f"6 x {number} = {6 * number}")
print(f"7 x {number} = {7 * number}")
print(f"8 x {number} = {8 * number}")
print(f"9 x {number} = {9 * number}")
print(f"10 x {number} = {10 * number}")
print(f"11 x {number} = {11 * number}")
print(f"12 x {number} = {12 * number}")